#!/bin/bash


mode=$1


if [ ! -d tamarin_v_loop ]
then
    mkdir tamarin_v_loop
fi
cd tamarin_v_loop

if [ $mode == "loop" ]
then
	for file in $(ls ../smartverif_examples) 
	do 
		echo $file
		theoryName=$(sed 's#.*/\([^\.]*\).*#\1#' <<<$file)
		{ time tamarin-prover --prove "../smartverif_examples/"$file --diff --output=$theoryName"_proof_loop.spthy"  +RTS -N10 -RTS > $theoryName"_complete" 2>&1 ; } 2>> $theoryName"_time"
	done
fi

if [ $mode == "noloop" ]
then
	for file in $(ls ../smartverif_examples) 
	do 
		echo $file
		theoryName=$(sed 's#.*/\([^\.]*\).*#\1#' <<<$file)
		{ time tamarin-prover --prove "../smartverif_examples/"$file --diff --output=$theoryName"_proof_no_loop"  +RTS -N10 -RTS > $theoryName"_no_loop_complete" 2>&1 ; } 2>> $theoryName"_no_loop_time"
	done
fi

if [ $mode == "smart" ]
then
	for file in $(ls ../smartverif_examples) 
	do 
		echo $file
		theoryName=$(sed 's#.*/\([^\.]*\).*#\1#' <<<$file)
		{ time ./smartverif "../smartverif_examples/"$file > $theoryName"_smartverif_complete" 2>&1 ; } 2>> $theoryName"_smartverif_time"
	done
fi

cd ..